// 在独立的本地预览浏览器中执行。会清空该测试浏览器的志愿和跟进数据。
// playwright-cli -s=hk5frontend run-code <本文件内容>
async page => {
  const passed = [];
  const check = (name, condition) => { if (!condition) throw new Error(name); passed.push(name); };
  await page.goto('http://127.0.0.1:8000/');
  await page.setViewportSize({width:1440,height:900});
  await page.getByRole('button', {name:/申请跟进/}).click();
  await page.evaluate(() => { window.HK5Store.clearAllTracks(); window.HK5App.replaceWish([], false); });
  await page.getByRole('button', {name:'浏览选校',exact:true}).click();
  await page.locator('#btnClearFacets').click();
  await page.locator('input[data-facet=uni][value=HKU]').check();
  await page.locator('input[data-facet=uni][value=CUHK]').check();
  check('学校多选并集 41 项', (await page.locator('#resCount').innerText()).startsWith('41'));
  await page.locator('input[data-facet=cat][value=金融]').check();
  check('方向选择后保留其他方向', await page.locator('input[data-facet=cat]').count() > 1);
  await page.locator('#btnClearFacets').click();
  const first = await page.locator('#results .pc').first().elementHandle();
  await page.locator('#btnMore').click();
  check('加载更多保留已有卡片节点', await first.evaluate(el=>el.isConnected));
  check('加载至 60 项', await page.locator('#results .pc').count() === 60);
  await page.locator('#results [data-act=wish]').first().click();
  check('加入志愿后保留按钮焦点', await page.locator('#results [data-act=wish]').first().evaluate(el=>el===document.activeElement));
  await page.locator('#results [data-act=wish]').nth(1).click();
  await page.getByRole('button', {name:/申请跟进/}).click();
  check('跟进页隐藏卡片表格切换', !await page.locator('.seg').isVisible());
  check('已有记录隐藏示例入口', !await page.locator('#tSeed').isVisible());
  await page.locator('[data-act=expand]').first().click();
  const note = '中'.repeat(700);
  await page.locator('textarea').first().fill(note);
  await page.waitForTimeout(800);
  check('备注停顿不失焦', await page.locator('textarea').first().evaluate(el=>el===document.activeElement));
  await page.locator('[data-act=mat]').first().check();
  check('材料进度即时更新', await page.locator('.material-count').first().innerText() === '1 / 7');
  await page.locator('[data-act=status]').first().selectOption('preparing');
  const yesterday = await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;});
  await page.locator('[data-act=deadline]').first().fill(yesterday);
  await page.locator('[data-act=rank]').first().focus();
  check('昨天截止标记过期', (await page.locator('.deadline-flag').first().innerText()).includes('已过期 1 天'));
  await page.locator('[data-act=clear]').first().click();
  await page.locator('#toast').getByRole('button',{name:'撤销'}).click();
  check('清空后撤销恢复备注', await page.locator('textarea').first().inputValue() === note);
  await page.locator('#q').fill('完全没有这个项目');
  check('跟进搜索实际过滤', await page.locator('#trackBody tr[data-row]').count() === 0);
  await page.locator('#q').fill('');
  await page.reload();
  await page.locator('[data-act=expand]').first().click();
  check('刷新后备注与材料保留', await page.locator('textarea').first().inputValue() === note && await page.locator('[data-act=mat]').first().isChecked());
  await page.locator('#btnWish').click();
  check('志愿单显示中文状态', (await page.locator('#wishList').innerText()).includes('准备材料'));
  await page.locator('#wSort').selectOption('rank');
  check('非手动排序禁用移动按钮', await page.locator('#wishList [data-act=up]').first().isDisabled());
  await page.keyboard.press('Escape');
  check('抽屉关闭恢复触发点焦点', await page.locator('#btnWish').evaluate(el=>el===document.activeElement));
  check('关闭抽屉不可交互', await page.locator('#drawer').evaluate(el=>el.inert));
  await page.getByRole('button',{name:'浏览选校',exact:true}).click();
  await page.locator('#results [data-act=modal]').first().click();
  await page.keyboard.press('Tab');
  check('弹窗焦点限制在内部', await page.locator('#modal').evaluate(el=>el.contains(document.activeElement)));
  await page.keyboard.press('Escape');
  check('详情关闭恢复按钮焦点', await page.locator('#results [data-act=modal]').first().evaluate(el=>el===document.activeElement));
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  const mobile = await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,resultY:document.querySelector('#results').getBoundingClientRect().top}));
  check('手机首屏有项目且无横向溢出', mobile.width === mobile.scrollWidth && mobile.resultY < 550);
  await page.locator('#btnFilters').click();
  await page.locator('input[data-facet=uni][value=HKU]').check();
  await page.locator('input[data-facet=uni][value=CUHK]').check();
  check('手机筛选支持多选', await page.locator('#filterDone').innerText() === '查看 41 个项目');
  await page.keyboard.press('Escape');
  check('筛选 Escape 关闭并恢复焦点', await page.locator('#btnFilters').evaluate(el=>el===document.activeElement));
  await page.screenshot({path:'output/playwright/after-mobile-browse.png'});
  await page.getByRole('button',{name:/申请跟进/}).click();
  check('手机跟进无横向溢出', await page.evaluate(()=>innerWidth===document.documentElement.scrollWidth));
  await page.screenshot({path:'output/playwright/after-mobile-track.png'});
  await page.setViewportSize({width:1440,height:900});
  await page.screenshot({path:'output/playwright/after-desktop-track.png'});
  return {passed:passed.length,checks:passed,mobile};
}
